class Background(object):
    def __init__(self, name):
        self.name = name
        self.description = ''
        self.prTraits = []
        self.ideals = []
        self.bonds = []
        self.flaws = []

    def getBackName(self):
        return self.name

    def setBackDesc(self,desc):
        self.description = desc
    def getBackDesc(self):
        return self.description

    def addPrTrait(self, trait):
        self.prTraits.append(trait)
    def getPrTraits(self):
        return self.prTraits

    def addIdeal(self, ideal):
        self.ideals.append(ideal)
    def getIdeals(self):
        return self.ideals

    def addBond(self, bond):
        self.bonds.append(bond)
    def getBonds(self):
        return self.bonds

    def addFlaw(self, flaw):
        self.flaws.append(flaw)
    def getFlaws(self):
        return self.flaws

acolyte = Background('Acolyte')
acolyte.setBackDesc('You have spent you life in the service of a temple or to a specific god or pantheon of gods. You act as an intermediary between the realm of the holy and the mortal world, performing sacred rites and offering sacrifices in order to conduct worshipers into the presence of the divine.\n')
acolyte.addPrTrait('I idolize a particular hero of my faith and constantly refer to that person\'s deeds and example.\n')
acolyte.addPrTrait('I can find common ground between the fiercest enemies, empathizing with them and always working toward peace.\n')
acolyte.addPrTrait('I see omens in every event and action. The gods try to speak to us, we just need to listen.')
acolyte.addPrTrait('Nothing can shake my optimistic attitude')
acolyte.addPrTrait('I quote (or misquote) sacred texts and proverbs in almost every situation.\n')
acolyte.addPrTrait('I am tolerant (or intolerant) of other faits and respect (or condemn) the worsip of other gods.\n')
acolyte.addPrTrait('I\'ve enjoyed fine food, drink, and high society among my temple\'s elite. Rough living grates on me.\n')
acolyte.addPrTrait('I\'ve spent so long in the temple that I have little practical experience dealing with people in the outside world.\n')
acolyte.addIdeal('The ancient traditions of worship and sacrifice must be preserved and upheld.\n')
acolyte.addIdeal('I alwyas try to help those in need, no matter what the personal cost.\n')
acolyte.addIdeal('We must help bring about the changes the gods are constantly working in the world.\n')
acolyte.addIdeal('I hope to one day rise to the top of my faith\'s religious hierarchy.\n')
acolyte.addIdeal('I trust that my deity will guide my actions. I have faith that if I work hard, things will go well.\n')
acolyte.addIdeal('I seek to prove myself worthy of by god\'s favor by matching my actions against his or her teachings.\n')
acolyte.addBond('I would die to recover an ancient relic of my faith that was lost long ago.\n')
acolyte.addBond('I will someday get revenge on the corrupt temple hierarchy who branded me a heretic.\n')
acolyte.addBond('I owe my life to the priest who took me in whem my parents died.\n')
acolyte.addBond('Everything i do is for the common people.')
acolyte.addBond('I will do anything to protect the temple where I served.')
acolyte.addBond('I seek to preserve a sacred text that my enemies consider heretical and seek to destroy.\n')
acolyte.addFlaw('I judge others harshly, and myself even more severely.\n')
acolyte.addFlaw('I put too much trust in those who wield power within my temple\'s hierarchy.\n')
acolyte.addFlaw('My piety sometimes leads me to blindly trust those that mrofess faith in my god.\n')
acolyte.addFlaw('I am inflexible in my thinking.\n')
acolyte.addFlaw('I am suspicious of strangers and expect the worst of them.\n')
acolyte.addFlaw('Once I pick a goal, I become obsessed with it to the detriment of everything else in my life.\n')

charlatan = Background('Charlatan')
charlatan.setBackDesc('You have always had a way with people. You know what makes them tick, you can tease out their hearts\' desires after a few minutes of conversation, and with a few leading questions you can read them like they were children\'s books. It\'s a useful talent, and one that you\'re perfectly willing to use for your advantage.\n')
charlatan.addPrTrait('I fall in and out of love easily, and am always pursuing someone.\n')
charlatan.addPrTrait('I have a joke for every occasion, especially occasions where humor is inappropriate.\n')
charlatan.addPrTrait('Flattery is my preferred trick for getting what I want.\n')
charlatan.addPrTrait('I\'m a born gambler who can\'t resist taking a risk for a potential payoff.\n')
charlatan.addPrTrait('I lie about almost everything, even when there\'s no good reason to.\n')
charlatan.addPrTrait('Sarcasm and insults are my weapons of choice.\n')
charlatan.addPrTrait('I keep multiple holy symbols on me and invoke whatever deity might come in useful at any given moment.\n')
charlatan.addPrTrait('I pocket anything i see tha tmight have some value.\n')
charlatan.addIdeal('I am a free spirit—no one tells me what to do.\n')
charlatan.addIdeal('I never target people who can\'t afford to lose a few coins.\n')
charlatan.addIdeal('I distribute the money i acquire to the people who really need it.\n')
charlatan.addIdeal('I never run the same con twice.\n')
charlatan.addIdeal('Material goods come and go. Bonds of friendship last forever.\n')
charlatan.addIdeal('I\'m determined to make something of myself.\n')
charlatan.addBond('I fleeced the wrong person and must work to ensure that this individual never crosses paths with me or those i care about.\n')
charlatan.addBond('I owe everything to my mentor—a horrible person who\'s probably rotting in jail somewhere.\n')
charlatan.addBond('Somewhere out there, I have a child who doesn\'t know me. I\'m making the world better for him or her.\n')
charlatan.addBond('I came from a noble family, and one day I\'ll reclaim my lands and title from those who stole them from me.\n')
charlatan.addBond('A powerful person killed someone I love. Some day soon, I\'ll have my revenge...\n')
charlatan.addBond('I swindled and ruined a person who didn\'t deserve it. I seek to atone for my misdeeds but might never be able to forgive myself.\n')
charlatan.addFlaw('I can\'t resist a pretty face.\n')
charlatan.addFlaw('I\'m always in debt. I spend my ill-gotten gains on decadent luxuries faster than I bring them in.\n')
charlatan.addFlaw('I\'m convinced that no one could ever fool me the way I fool others.\n')
charlatan.addFlaw('I\'m too greedy for my own good. I can\'t resist taking a risk if there\'s money involved.\n')
charlatan.addFlaw('I can\'t resist swindling people who are more powerful than me.\n')
charlatan.addFlaw('I hate to admit it and will hate myself for it, but I\'ll run and preserve my own hide if the going gets tough.\n')

criminal = Background('Criminal')
criminal.setBackDesc('You are an experienced criminal with a history of breaking the law. You have spent a lot of time among other criminals and still have contacts with the criminal underworld. You\'re far closer than most people to the world of murder, theft, and violence that pervades the underbelly of civilization, and you have survived up to this point by flounting the rules and regulations of society.\n')
criminal.addPrTrait('I always have a plan for what to do when things go wrong.\n')
criminal.addPrTrait('I am always calm, no matter what the situation. I never raise my voice or let my emotions control me.\n')
criminal.addPrTrait('The first thign i do in a new place is note the locations of everything valuable—or where cuch things coulg be hidden.\n')
criminal.addPrTrait('I would rather make a new friend than a new enemy.\n')
criminal.addPrTrait('I am incredibly slow to trust. Those who seep the fairest often have the most to hide.\n')
criminal.addPrTrait('I don\'t pay attention to the risks in a situation. Never tell me the odds.\n')
criminal.addPrTrait('The best way to get me to do something is to tell me I can\'t do it.\n')
criminal.addPrTrait('I blow up at the slightest insult.\n')
criminal.addIdeal('I don\'t steal from others in the trade.\n')
criminal.addIdeal('Chains are meant to be broken, as those who would forge them.\n')
criminal.addIdeal('I steal from the wealthy so that i can help people in need.\n')
criminal.addIdeal('I will do whatever it takes to become wealthy.\n')
criminal.addIdeal('I\'m loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care.\n')
criminal.addIdeal('There\'s a spark of good in everyone.\n')
criminal.addBond('I\'m trying to pay off an old debt I owe to a generous benefactor.\n')
criminal.addBond('My Ill-gotten gains go to support my family.\n')
criminal.addBond('Something important was taken from me, and I aim to steal it back.\n')
criminal.addBond('I will become the greatest thief that had ever lived.\n')
criminal.addBond('I\'m guilty of a terrible crime. I hope i can redeem myself for it.\n')
criminal.addBond('Someone I loved died becoues of a mistake I made. That will never happen again.\n')
criminal.addFlaw('When I see something valuable, I can\'t think about anything but how to steal it.\n')
criminal.addFlaw('When faced with a choice between money and my friends, I usually choose the money.\n')
criminal.addFlaw('If there\'s a plan, I\'ll forget it. If i don\'t forget it, I\'ll ignore it.\n')
criminal.addFlaw('I have a "tell" that reveals when I\'m lying.\n')
criminal.addFlaw('I turn tail and run when things look bad.\n')
criminal.addFlaw('An innocent person is in prison for a crime that I committed. I\'m ok with that.\n')

entertainer = Background('Entertainer')
entertainer.setBackDesc('You thrive in front of an audience. You know how to entrance them, entertain them, and even inspire them. Your poetics can stir the hearts of those who hear you, awakening greif or joy, laughter or anger. Your music raises the spirits or captures their sorrow. Your dance steps captivate, your humor cuts to the quick. Whatever techniques you use, your art is your life.\n')
entertainer.addPrTrait('I know a story relevant to almost every situation.\n')
entertainer.addPrTrait('Whenever I come to a new place, I collect local rumors and spread gossip.\n')
entertainer.addPrTrait('I’m a hopeless romantic, always searching for that “special someone.”\n')
entertainer.addPrTrait('Nobody stays angry at me or around me for long, since I can defuse any amount of tension.\n')
entertainer.addPrTrait('I love a good insult, even one directed at me.\n')
entertainer.addPrTrait('I get bitter if I’m not the center of attention.\n')
entertainer.addPrTrait('I’ll settle for nothing less than perfection.\n')
entertainer.addPrTrait('I change my mood or my mind as quickly as I change key in a song.\n')
entertainer.addIdeal('When I perform, I make the world better than it was.\n')
entertainer.addIdeal('The stories, legends, and songs of the past must never be forgotten, for they teach us who we are.\n')
entertainer.addIdeal('The world is in need of new ideas and bold action.\n')
entertainer.addIdeal('I\'m only in it for the money and fame.\n')
entertainer.addIdeal('I like seeing the smiles on people\'s faces whei I perform. That\'s all that matters.\n')
entertainer.addIdeal('Art should reflect the soul; it should come from within and reveal who we really are.\n')
entertainer.addBond('My instrument is my most treasured possession, and it reminds me of someone I love.\n')
entertainer.addBond('Someone stoll my precious instrument, and someday I\'ll get it back.\n')
entertainer.addBond('I want to become famous, whatever it takes.\n')
entertainer.addBond('I idolize a hero of the old tales and measures my deeds against that person\'s.\n')
entertainer.addBond('I will do anything to prove myelf superior to my hated rival.\n')
entertainer.addBond('I would do anything for the other members of my old troupe.\n')
entertainer.addFlaw('I\'ll do anything to win fame and renown.\n')
entertainer.addFlaw('I\'m a sucker for a pretty face.\n')
entertainer.addFlaw('A scandal prevents me from ever going home again. That kind of trouble seems to follow me around.\n')
entertainer.addFlaw('I once satirized a noble who still wants my head. It was a mistake that i will likely repeat.\n')
entertainer.addFlaw('I have trouble keeping my feelings hidden. My sharp tongue lands me in trouble.\n')
entertainer.addFlaw('Despite my best efforts, I am unreliable to my friends.\n')

folkHero = Background('Folk Hero')
folkHero.setBackDesc('You come from a humble social rank, but you are destined for so much more. Already the people of your home village regard you as their champion, and your destiny calls you to stand against the tyrants and monsters that threaten the common folk everywhere.\n')
folkHero.addPrTrait('I judge people by their actions, not their words.\n')
folkHero.addPrTrait('If someone is in trouble, I’m always ready to lend help.\n')
folkHero.addPrTrait('When I set my mind to something, I follow through no matter what gets in my way.\n')
folkHero.addPrTrait('I have a strong sense of fair play and always try to find the most equitable solution to arguments.\n')
folkHero.addPrTrait('I\'m confident in my own abilities and do what I can to instill confidence in others.\n')
folkHero.addPrTrait('Thinking is for other people. I prefer action.\n')
folkHero.addPrTrait('I misuse long words in an attempt to sound smarter.\n')
folkHero.addPrTrait('I get bored easily. When am I going to get on with my destiny?\n')
folkHero.addIdeal('Peole deserve to be treated with dignity and respect.\n')
folkHero.addIdeal('No one should get preferentail treatment before the law, and no one is above the law.\n')
folkHero.addIdeal('Tyrants must not be allowed to oppress the people\n')
folkHero.addIdeal('If I become strong, I can take what I want—What I deserve.\n')
folkHero.addIdeal('There\'s no good in pretending to be something I\'m not.\n')
folkHero.addIdeal('Nothing and no one can steer me away from my higher calling.\n')
folkHero.addBond('I have a family, but I have no idea where they are. One day, I hope to see them again.\n')
folkHero.addBond('I worked the land, I love the land, and I will protect the land.\n')
folkHero.addBond('A proud noble once gave me a horrible beating, and I will take my revenge on any bully I encounter.\n')
folkHero.addBond('My tools are symbols of my past life, and I carry them so that I will never forget my roots.\n')
folkHero.addBond('I protect those who cannot protect themselves.\n')
folkHero.addBond('I wish my childhood sweetheart had come with me to pursue my destiny.\n')
folkHero.addFlaw('The tyrant who rules my land will stop at nothing to see me killed.\n')
folkHero.addFlaw('I\'m convinced of the significance of my destiny, and blind to my shortcomings and the risk of failure.\n')
folkHero.addFlaw('The people who knew me when I was young know my shameful secret, so I can never go home again.\n')
folkHero.addFlaw('I have a weakness for the vices of the city, especially hard drink.\n')
folkHero.addFlaw('Secretly, I believe that things would be better if I were a tyrant lording over the land.\n')
folkHero.addFlaw('I have trouble trusting my allies.\n')

guildArtisan = Background('Guild Artisan')
guildArtisan.setBackDesc('You are a member of an artisan\'s guild, skilled in a particular field and closely associated with other artisans. You are a well-establishedpart of the mercantile world, freed by talent and wealth from the constraints of a feudal social order. You learned your skills as ans apprentice to a master artisan, under the sponsorship of your guild, untill you became a master in your own right.\n')
guildArtisan.addPrTrait('I believe that anything worth doing is worth doing right. I can\'t help it—I\'m a perfectionist.\n')
guildArtisan.addPrTrait('I\'m a snob who looks down on those who can\'t appreciate fine art.\n')
guildArtisan.addPrTrait('I always want to know how things work and what makes people tick.\n')
guildArtisan.addPrTrait('I\'m full of witty aphorisms and have a proverb for every occasion.\n')
guildArtisan.addPrTrait('I\'m rude to people who lack my commitment to hard work and fair play.\n')
guildArtisan.addPrTrait('I like to talk at length about my profession.\n')
guildArtisan.addPrTrait('I don\'t part with my money easily and will haggle tirelessly to get the best deal possible.\n')
guildArtisan.addPrTrait('I\'m well known for my work, and I want to make sure everyone appreciates it. I\'m always taken aback when people haven\'t heard o f me.\n')
guildArtisan.addIdeal('It is the duty of all civilized people to strengthen the bonds of community and the security of civilization.\n')
guildArtisan.addIdeal('My talents were given to me so that I could use them to benefit the world.\n')
guildArtisan.addIdeal('Everyone should be free to pursue his or her own livelihood.\n')
guildArtisan.addIdeal('I\'m only in it for the money.\n')
guildArtisan.addIdeal('I\'m committed to the people I care about, not to ideals.\n')
guildArtisan.addIdeal('I work hard to be teh best there is at my craft.\n')
guildArtisan.addBond('The workshop where I learned my trade is the most important place in the world to me.\n')
guildArtisan.addBond('I created a great work for someone, and then found them unworthy to receive it. I\'m still looking for someone worthy.\n')
guildArtisan.addBond('I owe my guild a great debt for forging me into the person I am today.\n')
guildArtisan.addBond('I pursue wealth to secure someone\'s love.\n')
guildArtisan.addBond('One day I will return to my guild and prove that I am the greatest artisan of them all.\n')
guildArtisan.addBond('I will get revenge on the evil forces that destroyed my place of business and ruined my livelihood.\n')
guildArtisan.addFlaw('I\'ll do anything to get my hands on something rare or priceless.\n')
guildArtisan.addFlaw('I\'m quick to assume that someone is trying to cheat me.\n')
guildArtisan.addFlaw('No one must ever learn that I once stole money from guild coffers.\n')
guildArtisan.addFlaw('I\'m never satisfied with what I have—I always want more.\n')
guildArtisan.addFlaw('I would kill to acquire a noble title.\n')
guildArtisan.addFlaw('I\'m horribly jealous of anyone who can outshine my handiwork. Everywhere I go, I\'m surrounded by rivals.\n')

hermit = Background('Hermit')
hermit.setBackDesc('You lived in seclusion—either in a sheltered community such as a monastery, or entirely alone—for a formative part of your life. In your time apart from the lcamor of society, you found quiety, solitude, and perhaps some of the answers you were looking for.\n')
hermit.addPrTrait('I\'ve been isolated for so long that I rarely speak, preferring gestures and the occasional grunt.\n')
hermit.addPrTrait('I am utterly serene, even in the face of disaster.\n')
hermit.addPrTrait('The leader of my community had something wise to say on every topic, and I am eager to share that wisdom.\n')
hermit.addPrTrait('I feel tremendous empathy for all who suffer.\n')
hermit.addPrTrait('I\'m oblivious to etiquette and social expectations.\n')
hermit.addPrTrait('I connect everything that happens to me to a grand, cosmic plan.\n')
hermit.addPrTrait('I often get lost in my own thoughts and contemplation, becoming oblivious to my surroundings.\n')
hermit.addPrTrait('I am working on a grand philosophical theory and love sharing my ideas.\n')
hermit.addIdeal('My gifts are meant to be shared with all, not used for my own benefit.\n')
hermit.addIdeal('Emotions must not cloud our sense of what is right and true, or our logical thinking.\n')
hermit.addIdeal('Inquiry and curiosity are the pillars of progress.\n')
hermit.addIdeal('Solitude and contemplation are paths toward mystical or magical power.\n')
hermit.addIdeal('Meddling in the affairs of others only causes trouble.\n')
hermit.addIdeal('If you know yourself, there\'s nothing left to know.\n')
hermit.addBond('Nothing is more important to me than the other members of my hermitage, order, or association.\n')
hermit.addBond('I entered seclusion to hide frome the ones who might still be hunting me. I must someday confront them.\n')
hermit.addBond('I\'m still seeking the enlightenment I pursued in my seclusion, and it still eludes me.\n')
hermit.addBond('I entered seclusion because I loved someone I could not have.\n')
hermit.addBond('Should my discovery come to light, it could bring ruin to the world.\n')
hermit.addBond('My isolation gave me great insight into a great evil that only I can destroy.\n')
hermit.addFlaw('Now that I\'ve returned to the world, I enjoy its delights a little too much.\n')
hermit.addFlaw('I harbor dark, bloodthirsty thoughts that my isolation and meditation failed to quell.\n')
hermit.addFlaw('I am dogmatic in my thoughts and philosophy.\n')
hermit.addFlaw('I let my need to win arguments overshadow friendships and harmony.\n')
hermit.addFlaw('I\'d risk too much to uncover a lost bit of knowledge.\n')
hermit.addFlaw('I like keeping secrets and won\'t share them with anyone.\n')

noble = Background('Noble')
noble.setBackDesc('You understand wealth, power, and privilege. You carry a noble title, and your family owns land, collects taxes, and wields significant political influence. You might be a pampered aristocrat unfamiliar with work or discomfort, a former merchant just elevated to the nobility, or a disinherited scoundrel with a disproportionate sense of entitlement. Or you could be an honest, hard-working landowner who cares deeply about the people who live and work on your land, keenly aware of your responsibility to them.\n')
noble.addPrTrait('My eloquent flattery makes everyone I talk to feel like the most wonderful and important person in the world.\n')
noble.addPrTrait('The common folk love me for my kindness and generosity.\n')
noble.addPrTrait('No one could doubt by looking at my regal bearing that I am a cut above the unwashed masses.\n')
noble.addPrTrait('I take great pains to always look my best and follow the latest fashions.\n')
noble.addPrTrait('I don\'t like to get my hands dirty, and I won\'t be caught dead in unsuitable accommodations.\n')
noble.addPrTrait('Despite my noble birth, I do not place myself above other folk. We all have the same blood.\n')
noble.addPrTrait('My favor, once lost, is lost forever.\n')
noble.addPrTrait('If you do me an injury, I will crush you, ruin your name, and salt your fields.\n')
noble.addIdeal('Respect is due to me because of my position, but all people regardless of station deserve to be treated with dignity.\n')
noble.addIdeal('It is my duty to respect the authority of those aboce me, just as those below me must respect mine.\n')
noble.addIdeal('I must prove that I can handle myself without the coddling of my family.\n')
noble.addIdeal('If I can attain more power, no one will tell me what to do.\n')
noble.addIdeal('Blood runs thicker than water.\n')
noble.addIdeal('It is my duty to protect and care for the people beneth me.\n')
noble.addBond('I will face any challenge to win the approval of my family.\n')
noble.addBond('My house\'s alliance with another noble family must be sustained at all costs.\n')
noble.addBond('Nothing is more important than the other members of my family.\n')
noble.addBond('I am in love with the heir of a family that my family despises.\n')
noble.addBond('My loyalty to my soverign is unwabering.\n')
noble.addBond('The common folk must see me as a hero of the people.\n')
noble.addFlaw('I secretly believe that everyone is beneath me.\n')
noble.addFlaw('I hide a truly scandalous secret that could ruin my family forever.\n')
noble.addFlaw('I too often hear veiled insults and threats in every word addressed to me, and I\'m quick to anger.\n')
noble.addFlaw('I have an insatiable desire for carnal pleasures.\n')
noble.addFlaw('In fact, the world does revolve around me.\n')
noble.addFlaw('By my words and actions, I often bring shame to my family.\n')

outlander = Background('Outlander')
outlander.setBackDesc('You grew up in the wilds, far from civilization and the comforts of town and technology. You\'ve witnessed the migration of herds larger than forests, survived weather more extreme than any city-dweller could comprehend, and enjoyed the solitude of being the only thinking creature for miles in any direction. The wilds are in your blood, wheather you were a nomad, an explorer, a recluse, a hunter-gatherer, or even a marauder. Even in places where you don\'t know the specific features of the terrain, you know the ways of the wild.\n')
outlander.addPrTrait('I\'m driven by a wanderlust that led me away from home.\n')
outlander.addPrTrait('I watch over my friends as if they were a litter of newborn pups.\n')
outlander.addPrTrait('I once ran twenty-five miles without stopping to warn my clan of an approaching orc horde. I\'d do it again if I had to.\n')
outlander.addPrTrait('I have a lesson for every situation, drawn from observing nature.\n')
outlander.addPrTrait('I place no stock in wealthy or well-mannered folk. Money and manners won\'t save you from a hungry owlbear.\n')
outlander.addPrTrait('I\'m always picking things up, absently fiddling with them, and sometimes accidentally breaking them.\n')
outlander.addPrTrait('I feel far more comfortable around animals than people.\n')
outlander.addPrTrait('I was, in fact, raised by wolves.\n')
outlander.addIdeal('Life is like the seasons, in constant change, and we must change with it.\n')
outlander.addIdeal('It is each person\'s responsibility to make the most happiness for the whole tribe.\n')
outlander.addIdeal('If I dishonor myself, then I dishonor my whole clan.\n')
outlander.addIdeal('The strongest are meant to rule.\n')
outlander.addIdeal('The natural world is more important than all the constraints of civilization.\n')
outlander.addIdeal('I must earn glory in battle, for myself and my clan.\n')
outlander.addBond('My family, clan, or tribe is the most important thing in my life, even when they are far from me.\n')
outlander.addBond('An injury to the unspoiled wilderness of my home is an injury to me.\n')
outlander.addBond('I will bring terrible wrath down on the evildoers who destroyed my homeland.\n')
outlander.addBond('I am the last of my tribe, and it is up to me to ensure their names enter legend.\n')
outlander.addBond('I suffer awful visions of a coming disaster and will do anything to prevent it.\n')
outlander.addBond('It is my duty to provide children to sustain my tribe.\n')
outlander.addFlaw('I am too enamored of ale, wine, and other intoxicants.\n')
outlander.addFlaw('There\'s no room for caution in a life lived to the fullest.\n')
outlander.addFlaw('I remeber every insult I\'ve received and nurse a silent resentment toward anyone who\'s ever wronged me.\n')
outlander.addFlaw('I am slow to trust members of other races, tribes, and societies.\n')
outlander.addFlaw('Violence is my answer to almost any challange.\n')
outlander.addFlaw('Don\'t expect me to save those who can\'t save themselves. It is nature\'s way that the strong thrive and the weak perish.\n')

sage = Background('Sage')
sage.setBackDesc('You spent years learning the lore of the multiverse. You scoured manuscripts, studie scrolls, and listened to the greatest experts on the subjects that interest you. Your efforts have made you a master in your fields of study.\n')
sage.addPrTrait('I use polysyllabic words that convey the empression of great erudition.\n')
sage.addPrTrait('I\'ve read every book in the world\'s greatest libraries—or I like to boast that I have.\n')
sage.addPrTrait('I\'m used to helping out those who aren\'t as smart as I am, and I patiently explain anything and everything to others.\n')
sage.addPrTrait('There\'s nothing I like more than a good mystery.\n')
sage.addPrTrait('I\'m willing to listen to every side of an argument before I make my own judgment.\n')
sage.addPrTrait('I . . . speak . . . slowly . . . when talking . . . to idiots, . . . which . . . almost . . . everyone . . . is . . . compared . . . to me.\n')
sage.addPrTrait('I am horribly, horribly awkward in social situations.\n')
sage.addPrTrait('I\'m convinced that people are always trying to steal my secrets.\n')
sage.addIdeal('The path to power and self-improvement is through knowledge.\n')
sage.addIdeal('What is beautiful points us beyond itself toward what is true.\n')
sage.addIdeal('Emotions must not cloud our logical thinking.\n')
sage.addIdeal('Hothing should fetter the infinite possibility inherent in all existance.\n')
sage.addIdeal('Knowledge is the path to power and domination.\n')
sage.addIdeal('The goal of a life of study is the betterment of oneself.\n')
sage.addBond('It is my duty to protect my students')
sage.addBond('I have an ancient text that holds terrible secrets that must not fall into the wrong hands.\n')
sage.addBond('I work to preserve a library, university, scriptorium, or monastery.\n')
sage.addBond('My life\'s work is a series of tomes related to a specific field of lore.\n')
sage.addBond('I\'ve been searching my whole life for the answer to a certain question.\n')
sage.addBond('I sold my soul for knowledge. I hope to do great deeds and win it back.\n')
sage.addFlaw('I am easily distracted by the promise of information.\n')
sage.addFlaw('Most people scream and run when they see a demon, I stop and take notes on its anatomy.\n')
sage.addFlaw('Unlocking an ancient mystery is worth the price of a civilization.\n')
sage.addFlaw('I overlook obvious solutions in favor of complicated ones.\n')
sage.addFlaw('I speak without really thinking through my words, invariably insulting others.\n')
sage.addFlaw('I can\'t keep a secret to save my life, or anyone else\'s.\n')

sailor = Background('Sailor')
sailor.setBackDesc('You sailed on a seagoing vessel for years. In that time, you faced down mighty storms, monsters of the deep, and those who wanted to sink your craft to the bottomless depths. Your first love is the distant line of the horizon, but the time has come to try your hand at something new.\n')
sailor.addPrTrait('My friends know they can rely on me, no matter what.\n')
sailor.addPrTrait('I work hard so that I can play hard when the work is done.\n')
sailor.addPrTrait('I enjoy sailing into new ports and making new friends over a flagon of ale.\n')
sailor.addPrTrait('I stretch the truth for the sake of a good story.\n')
sailor.addPrTrait('To me, a tavern brawl is a nice way to get to know a new city.\n')
sailor.addPrTrait('I never pass up a friendly wager.\n')
sailor.addPrTrait('My language is as foul as an otyuggh nest.\n')
sailor.addPrTrait('I like a job well done, especially if I can convince someone else to do it.\n')
sailor.addIdeal('The thing that keeps a ship together is mutual respect between captain and crew.\n')
sailor.addIdeal('We all do the work, so we all share in the rewards.\n')
sailor.addIdeal('The sea is freedom—the freedom to go anywhere and do anything.\n')
sailor.addIdeal('I\'m a predator, and the other ships on the sea are my prey.\n')
sailor.addIdeal('I\'m committed to my crewmates, not to ideals.\n')
sailor.addIdeal('Someday I\'ll own my own ship and chart my own destiny.\n')
sailor.addBond('I\'m loyal to my captain first, everything else second.\n')
sailor.addBond('The ship is most important—crewmates and captains come and go.\n')
sailor.addBond('I\'ll always remember my first ship.\n')
sailor.addBond('In a harbor town, I have a paramour whose eyes nearly stole me from the sea.\n')
sailor.addBond('I was cheated out of my fair share of the profits, and I want to get my due.\n')
sailor.addBond('Ruthless pirates murdered my captain and crewmates, plundered our ship, and left me to die. Vengeance will be mine.\n')
sailor.addFlaw('I follow orders, even if I think they\'re wrong.\n')
sailor.addFlaw('I\'ll say anything to avoid having to do extra work.\n')
sailor.addFlaw('Once someone questions my courage, I never back down no matter how dangerous the situation.\n')
sailor.addFlaw('Once I start drinking, it\'s hard for me to stop.\n')
sailor.addFlaw('I can\'t help but pocket loose coins and other trinkets I come across.\n')
sailor.addFlaw('My pride will probably lead to my destruction.\n')

soldier = Background('Soldier')
soldier.setBackDesc('War has been your life for as long as you care to remember. You trained as a youth, studied the use of weapons and armor, learned basic survival techniques, including how to stay alive on the battlefield. You might have been part of a standing national army or a mercenary company, or perhaps a memver of a local militia who rose to prominence during a recent war.\n')

urchin = Background('Urchin')
urchin.setBackDesc('You grew up on the streets alone, orphaned, and poor. You had no one to watch over you or to provide for you, so you learned to provide for yourself. You fought fiercely over food and kept a constant watch out for other desperate souls who might steal from you. You slept on rooftops and in alleyways, exposed to the elements, and endured sickness without the advantage of medicine or a place to recuperate. You\'ve survived despite all odds, and did so through cunning, strength, speed, or some combination of each.\n')
#urchin.addPrTrait()
backgroundList = [acolyte,charlatan,criminal,entertainer,folkHero,guildArtisan,hermit,noble,outlander,sage,sailor,soldier,urchin]